# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'



target 'EatinApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 pod 'SDWebImage', '~>3.7'
 pod 'AFNetworking', '< 2.6.1'
 pod 'MBProgressHUD'
  # Pods for EatinApp

  target 'EatinAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
